# Generated by Django 4.2.1 on 2023-06-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubik', '0002_alter_persona_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
